### ISSUE TITLE
Problem with commands

### ISSUE THREAD

**Issue by MiaCompiling** [LARG/HFO#101]
HI, @mhauskn , you see, when I run all the .sh files, they all work fine, but when I try to type command manually, it seems unable to connect to the agent. The following picture is when I use command "./bin/HFO --offense-npcs=2 --defense-agents=1 --defense-npcs=1 --trials 20 --no-sync --port=7000 & (./hand_coded_defense_agent &> agent1.txt &)" under the main HFO directory, there is a missing defense-agent.
How can i address this problem? Does it mean that I can only use .sh file to run the program?
![image](https://user-images.githubusercontent.com/59831989/82683055-e337fc00-9c82-11ea-915f-b528339afc48.png)

**Comment by mhauskn** [comment]
I would recommend using two separate terminal windows. In the first launch the server:
./bin/HFO --offense-npcs=2 --defense-agents=1 --defense-npcs=1 --trials 20 --no-sync --port=7000

Then in the second window, launch the agent:
./hand_coded_defense_agent > agent1.txt

**Comment by MiaCompiling** [comment]
Thanks, it works!
