### ISSUE TITLE
How to print info

### ISSUE THREAD

**Issue by MoonieC** [LARG/HFO#104]
Hi, @mhauskn , after I have done writing my own code, how can I debug?
And, I noticed that when I try to print something on the screen using print(), it doesn't show up in terminal, so where can I find the info I want to print?

**Comment by mhauskn** [comment]
Hmm, it should print, unless you're redirecting the output or looking at the wrong terminal?

**Comment by MiaCompiling** [comment]
I think it only print things in the Trainer.py, but things in the xxxx_agent.py it doesn't print.
How can I print things in the agent.py?

**Comment by MoonieC** [comment]
I changed my command and it finally comes out, Thanks!

**Comment by MoonieC** [comment]
I changed my command and it finally comes out, Thanks!
