### ISSUE TITLE
Adding features

### ISSUE THREAD

**Issue by arminsadreddin** [LARG/HFO#111]
I am looking to add some features into HFO state such as players' posCount.
I have changed the HFO/src folder and add my features in the feature_extractor.cpp, afterwards I just remake the project again using the following commands:
**mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=RelwithDebInfo ..
make -j4
make install**
But it does not seem to work and I can not get my features.
How should I make the HFO again in order to recognize my changes ?

**Comment by tamurajunichi** [comment]
I solved this problem by changing the numFeatures in [https://github.com/LARG/HFO/blob/master/src/lowlevel_feature_extractor.cpp#17](url).
