### ISSUE TITLE
Python versions usable - document, perhaps in setup.py?

### ISSUE THREAD

**Issue by drallensmith** [LARG/HFO#26]
Hi. What Python versions does/should HFO work with? (3.X only, 2.7 + 3.X, or what?) And would it be usable with cython (probably using [cython.py with pure-python code](http://docs.cython.org/en/latest/src/tutorial/pure.html#magic-attributes))? I suggest putting this in setup.py's classifiers and/or in the README.

(I am partially confused on this by seeing, on the one hand, various things that are only for python 3.X, such as print functions without from `__future__ import print_function`, but on the other hand example/python_agents_3v3.sh is trying both python2.7 and python3.)

Thanks,

-Allen

**Comment by mhauskn** [comment]
HFO should work with python 2.7+ and 3.X. I'm unsure if it would or
wouldn't be usable or not with cython. Happy to accept PR with edits to
setup.py & README.

**Comment by drallensmith** [comment]
Thanks (I'll be asking some further questions shortly...); PR done (#27).

-Allen
