### ISSUE TITLE
Low-level Center Field (31-33) Landmark is not center of HFO playable area

### ISSUE THREAD

**Issue by drallensmith** [LARG/HFO#37]
It is actually the center of the *RoboCup* playable area. In `lowlevel_feature_extractor.cpp`:

`// Corners of the playable area`
`rcsc::Vector2D centerField(0, 0)`

That should be something like `centerField((pitchHalfLength/2), 0)`.

The only problem I can see with simply fixing it is that it would mess up agents - in particular learning agents - that are using it already.

**Comment by mhauskn** [comment]
Yes, this is the center of the entire field (rather than the playable HFO area). As such, it is the midpoint of the left field boundary of the HFO area. It probably should be better clarified as such, but I don't think it's a problem.

**Comment by drallensmith** [comment]
OK, will fix as part of my current documentation work. (It's a problem if one doesn't realize this and bases testing code on the other interpretation...)
