### ISSUE TITLE
Ordering of Teammate and Opponent Features in High Level Feature Set

### ISSUE THREAD

**Issue by DurgeshSamant** [LARG/HFO#56]
It would be great if someone can clarify the ordering of the teammate and opponent features returned in the High Level Feature Set.

When the Fullstate flag is ON, they seem to be ordered by uniform numbers.

When the Fullstate flag is OFF, they seem to be ordered by perceived proximity.

1. Is this interpretation correct?
2. If so, are the two orderings deliberately different?

**Comment by mhauskn** [comment]
Uniform numbers are populated by iterating over the list of teammates/opponents which are ordered according to distance from the agent:
https://github.com/LARG/HFO/blob/master/src/lowlevel_feature_extractor.cpp#L193

I don't know why Fullstate causes order by uniform number.

**Comment by DurgeshSamant** [comment]
However, the 'high' level feature extractor does not seem to do any such ordering
https://github.com/LARG/HFO/blob/fe8994416a00ae5ee6eb8837fea23d7e543df3e3/src/highlevel_feature_extractor.cpp#L33

**Comment by mhauskn** [comment]
For sake of consistency, wm.opponentsFromSelf() would be better.

**Comment by DurgeshSamant** [comment]
fixed by PR #57
