### ISSUE TITLE
Unable to Run HFO!

### ISSUE THREAD

**Issue by grossmanlev** [LARG/HFO#59]
Hello, I have just installed HFO on Ubuntu 16.04.  However, when I try to run any of the demo scripts, I get this error:

`[start.py] Cleaning up server and other processes
Traceback (most recent call last):
  File "./bin/HFO", line 235, in <module>
    main(parseArgs())
  File "./bin/HFO", line 112, in main
    %(serverCommand + serverOptions)
AssertionError: [start.py] Failed to launch Server with command: "/home/robocup/HFO/bin/rcssserver server::port=6000 server::coach_port=6001 server::olcoach_port=6002 server::coach=1 server::game_logging=1 server::text_logging=1 server::hfo_logging=1 server::hfo_log_dir=log/ server::game_log_dir=log/ server::text_log_dir=log/ server::synch_mode=0 server::hfo=1 server::fullstate_l=0 server::fullstate_r=0 server::coach_w_referee=1 server::hfo_max_trial_time=1000 server::hfo_max_trials=-1 server::hfo_max_frames=-1 server::hfo_offense_on_ball=0 server::random_seed=-1 server::hfo_max_untouched_time=100 server::hfo_min_ball_pos_x=0.000000 server::hfo_max_ball_pos_x=0.200000 server::hfo_min_ball_pos_y=-0.800000 server::hfo_max_ball_pos_y=0.800000 server::say_msg_size=1000 server::record_messages=0"

Another rcssserver may be running on the same port?
Try: "killall -9 rcssserver"
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "./bin/HFO", line 24, in cleanup
    p.terminate()
  File "/usr/lib/python2.7/subprocess.py", line 1567, in terminate
    self.send_signal(signal.SIGTERM)
  File "/usr/lib/python2.7/subprocess.py", line 1562, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "./bin/HFO", line 24, in cleanup
    p.terminate()
  File "/usr/lib/python2.7/subprocess.py", line 1567, in terminate
    self.send_signal(signal.SIGTERM)
  File "/usr/lib/python2.7/subprocess.py", line 1562, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process
`

Any ideas how to fix this issue?  Note, prior to installing this, I had already install rcssserver and rcsmonitor.  Could this be the issue?

**Comment by DurgeshSamant** [comment]
The following might help
1. Reinstall HFO. [completely remove the HFO directory, clone the repo, compile and install again]
2. before invoking a script. kill any previous rcssservers by running 'killall -9 rcssserver' 
3. Check if the paths to the HFO server and the agents in the script are correct. They may become invalid if the script is invoked from some other location.

Why script are you trying to invoke? (and from which directory?)

**Comment by obsproth** [comment]
I was in the same situation.

>Note, prior to installing this, I had already install rcssserver and rcsmonitor. Could this be the issue?
Yes, delete .conf files in `/home/[your name here]/.rcssserver/`

**Comment by grossmanlev** [comment]
Thanks!  Fixed
