### ISSUE TITLE
Way to Speed Up Simulator?

### ISSUE THREAD

**Issue by grossmanlev** [LARG/HFO#60]
Hello, 

I am looking to do some RL training on an agent.  However, the simulator is currently pretty slow, especially to do something like Q-Learning.  Is there a way to speed up the simulator/make the graphical agent now show (if that's the slow-down)?

EDIT: Headless doesn't seem to make it go any faster.  Also, for reference, I am using attacker npcs -- is this the cause of the slowness?  As npcs on their own are also as slow as my learning agent.

Thanks!

**Comment by mhauskn** [comment]
The ways to speedup the code:
1) Make sure you're building with "cmake -DCMAKE_BUILD_TYPE=RelwithDebInfo"
or "Release".
2) Disable sync mode (add flag --no-sync)
3) Disable Soccerwindow (add flag --headless)

It should run at several hundred FPS, depending on the number of players
you have activated.

**Comment by grossmanlev** [comment]
Well, I have build with "RelwithDebInfo," and I am running the following command:

./bin/HFO --defense-npcs=2 --offense-npcs=2 --no-sync --fullstate --headless

However, it takes about 4 seconds per every 100 frames or so.

**Comment by mhauskn** [comment]
Sorry, you'll want to remove the --no-sync flag and it should go much
faster.

**Comment by grossmanlev** [comment]
Oh great!  Thank you so much!
