### ISSUE TITLE
proximity features in high-level state space are negative

### ISSUE THREAD

**Issue by CoolPhilChen** [LARG/HFO#68]
Hi @mhauskn !
According to the manual, feature 6 in high-level state feature list is "_Goal Center Proximity - Agent’s proximity to the center of the goal_". Here are some values of this feature I got in practice
```
array([ 0.09794438,  0.06624234,  0.03432488,  0.00357747, -0.02914906,
       -0.05965102, -0.09055936, -0.12043804, -0.14975351, -0.17937934],
      dtype=float32)
```
According to my understanding (which might be wrong), "_proximity_" features should have non-negative value. Could you please tell me how these "_proximity_" features are computed? Or tell me where I can find the code for generating these state features?
Thank you very much!

**Comment by mhauskn** [comment]
https://github.com/LARG/HFO/blob/master/src/highlevel_feature_extractor.cpp#L77

**Comment by CoolPhilChen** [comment]
Great. Thanks a lot!
