### ISSUE TITLE
/usr/bin/env: "python": No such file or directory

### ISSUE THREAD

**Issue by MiaCompiling** [LARG/HFO#99]
Hi @mhauskn , sorry to bother you again.

I think I have successfully fullfilled the steps to install this HFO enviroment, but when I try the demos, "./example/passing_agents.sh", it says "/usr/bin/env: "python": No such file or directory" as follows:
![image](https://user-images.githubusercontent.com/59831989/82570146-cb457700-9bb3-11ea-94c4-f47583922147.png)

**Comment by MiaCompiling** [comment]
By the way, my python version is 3.6.9 and pip3, I didn't install pip. And I use the "pip3 install ." to interface python. Is this the problem?

**Comment by mhauskn** [comment]
A few options you could try: ```python3 example/passing_agents.sh```

Or change the string to be "/usr/bin/env python3".

Or symlink your python3: ```sudo ln -s /usr/bin/python3 /usr/bin/python```

**Comment by MiaCompiling** [comment]
Thank you soooo much! I tried method NO.3 and it solved!
